apiVersion: v1
kind: Pod
metadata:
  name: my-sql
  labels:
    app: my-sql
spec:
  containers:
  - name: my-sql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: MYSQL_DATABASE
